# jekyll config

remote_theme: b2a3e8/jekyll-theme-console
markdown: kramdown

title: 'mel'
description: >
  a wise woman once said "fuck this shit" and she lived happily ever after

baseurl: ""
url: "https://mel.sh"

header_pages:
  - index.md
  - about.md

style: light
listen_for_clients_preferred_style: false

footer: '<a href="https://write.mel.sh" target="_blank">blog</a> <a href="https://todon.nl/@mel" target="_blank">rant</a> <a href="https://github.com/bellaweo" target="_blank">code</a>'

plugins:
  - jekyll-seo-tag
